# This file was generated by GoReleaser. DO NOT EDIT.
cask "polign" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "d36c9313663278989575fd21085f13169f585fe65efd1f6b08fe1426392917b0"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "09231c691d7ab15a4d3db1f50f48ba92a7afb40c59e44f2223dae895b9119a38"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "93a7bcda0f34120543d9659d16d9465f5a26522fb37d5507c2df6e373bb2f2aa"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa4f441736b0e29a2113c4c99d06287819b00b75a69c01357ab5221be43ccdbf"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_amd64.tar.gz"
    end
  end

  name "polign"
  desc "Object-store-native vector database: static tools, durability from your own bucket"
  homepage "https://polign.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polign"
  binary "polign-server"
  binary "polign-persistor"
  binary "polign-apikey"
  binary "polign-maintain"
  binary "polign-import"

  postflight do
    if OS.mac?
      %w[polign polign-server polign-persistor polign-apikey polign-maintain polign-import].each do |b|
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
