# This file was generated by GoReleaser. DO NOT EDIT.
cask "polign" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "a0e591149a65bd0fb153ab359103b1cec9296ec1d2ae6ec7d39acb8f64ee1435"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0dfecc95c11186eceda78f4a55b6038fa887877a2d9dc49aec9c0c1ea2cb2b7a"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0bb508ea90698564ca7aa2a31bac209d08086d99def2ee4c990b1003039f94d6"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "adaf7d6f2b49dce4bb9478f308673236a4bd66de10e102d36d1d439325b6c4cb"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_amd64.tar.gz"
    end
  end

  name "polign"
  desc "Object-store-native vector database: static tools, durability from your own bucket"
  homepage "https://polign.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polign"
  binary "polign-server"
  binary "polign-persistor"
  binary "polign-apikey"
  binary "polign-maintain"
  binary "polign-import"

  postflight do
    if OS.mac?
      %w[polign polign-server polign-persistor polign-apikey polign-maintain polign-import].each do |b|
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
