# This file was generated by GoReleaser. DO NOT EDIT.
cask "polign" do
  version "0.14.0"

  on_macos do
    on_arm do
      sha256 "02b5db5f1ae8e32bf4e04348bdd22de0e2510b435dff1d5ee7614ffb6c3d1fa7"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "926e3347f8ee787c659e86a0fa5f0885688c6649c588ef21fed9f899ed3e43c5"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b7727036b1b3c40886fc47d3dd7aa3e9cb788cdaea4c03c5ba08100c8d27c85f"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4871228cf95cb763281157a127f4338e11738e418e90a515e5c9f3ad4b01d675"
      url "https://github.com/Polign/polign/releases/download/v#{version}/polign_db_linux_amd64.tar.gz"
    end
  end

  name "polign"
  desc "Object-store-native vector database: static tools, durability from your own bucket"
  homepage "https://polign.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "polign"
  binary "polign-server"
  binary "polign-persistor"
  binary "polign-apikey"
  binary "polign-maintain"
  binary "polign-import"

  postflight do
    if OS.mac?
      %w[polign polign-server polign-persistor polign-apikey polign-maintain polign-import].each do |b|
        system_command "/usr/bin/xattr",
                       args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{b}"]
      end
    end
  end

  # No zap stanza required
end
