# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.12.0"

  on_macos do
    on_arm do
      sha256 "e775f1c04aa7bf7d74a430ef0a9cbaf4e6916998473c1bb22cfd61494fec5dc1"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc2b28bbfdf3d146275cb10a1cd49877d263e146fe58e5b2284517651fcc9026"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d0fead2043608365fce5ca65a14dbef40fe472d03e8d5215a69f7d32535a99ca"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ca666bf2d80557b07a9ac9272a8e8cd4b94a0655b591d975974b40ae4461204"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_linux_amd64.tar.gz"
    end
  end

  name "recall"
  desc "Typed, correctable agent memory over MCP, kept in your own polign_db"
  homepage "https://polign.com/recall"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "polign/tap/polign",
    ]

  binary "recall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/recall"]
    end
  end

  # No zap stanza required
end
