# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "569c02cbc8bfe8484aec65f61072d2a10142795367488138e2ef09f8500446a1"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "61d5d7dec68a795a3c8a9ed97e32f25f110adc709176c3b51cdb73679eacedd5"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "85388afdef730f3250c7bd5405015383e502586fa76d4cf891d76051d67637a6"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b94daf45f0afe2d656bf753855a249af319224e3a25c70c783ec3c07ce8b06ce"
      url "https://github.com/Polign/recall/releases/download/v#{version}/recall_linux_amd64.tar.gz"
    end
  end

  name "recall"
  desc "Typed, correctable agent memory over MCP, kept in your own polign_db"
  homepage "https://polign.com/recall"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "polign/tap/polign",
    ]

  binary "recall"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/recall"]
    end
  end

  # No zap stanza required
end
